### ISSUE TITLE
Getting GS402: Invalid request

### ISSUE THREAD

**Issue by vasani-arpit** [geosparks/geospark-cordova-example#4]
Thanks for resolving #3 

Now I am getting ```GS402: Invalid request``` error while initialization of the plugin. 

![image_2019_11_26T09_54_22_869Z](https://user-images.githubusercontent.com/6497827/69619017-e7cb8100-1060-11ea-9112-e4635994a0d5.png)

Here is the steps I performed 

1. Cloned the project
2. Replace publishable key
3. cordova platform remove android
3. added 2 lines mentioned in #3 
4. cordova platform add android
5. cordova platform build android

Thanks in advance.

**Comment by jothipriyadharshanr** [comment]
> Thanks for resolving #3
> 
> Now I am getting `GS402: Invalid request` error while initialization of the plugin.
> 
> ![image_2019_11_26T09_54_22_869Z](https://user-images.githubusercontent.com/6497827/69619017-e7cb8100-1060-11ea-9112-e4635994a0d5.png)
> 
> Here is the steps I performed
> 
> 1. Cloned the project
> 2. Replace publishable key
> 3. cordova platform remove android
> 4. added 2 lines mentioned in #3
> 5. cordova platform add android
> 6. cordova platform build android
> 
> Thanks in advance.

The package name of your application has to be same with what you have used to create application in GeoSpark. 

Let me know if that works.

**Comment by vasani-arpit** [comment]
Thanks. It works. Sorry for foolish questions. (It will up your github ranking though ;) )

**Comment by jothipriyadharshanr** [comment]
> Thanks. It works. Sorry for foolish questions. (It will up your github ranking though ;) )

It was a valid query. Our next SDK release will support all error codes which will give proper error description. We are happy to help you guys.
